### ISSUE TITLE
CustomControl binding position does not listen to changes in bindingPosition

### ISSUE THREAD

**Issue by MehdiSaffar** [googlemap-react/googlemap-react#14]
I discovered this while working on a responsive layout. When the screen is wide I set the binding position of my component to TOP_CENTER but when the screen is narrow I set the binding position to BOTTOM_CENTER. The change does not happen.

Looking in the CustomControl component the useEffect does not seem to depend on the bindingPosition only on the map itself.

**Comment by lucifer1004** [comment]
I had a few attempts, but it is a bit difficult to implement.
Google Map JS SDK does not offer a direct way to manipulate `google.maps.Map.controls`, so I had to manually manipulate the `google.maps.MVCArray` object and this resulted in a series of unexpected behaviors.

**Comment by lucifer1004** [comment]
Should be fixed by 5550e11
