### ISSUE TITLE
Use with TypeScript

### ISSUE THREAD

**Issue by thejahweh** [googlemap-react/googlemap-react#16]
![image](https://user-images.githubusercontent.com/10514993/62374952-685bf400-b53d-11e9-9778-c430ac9daf11.png)

Editor is PHPStorm.

**Comment by lucifer1004** [comment]
Could you please share your `tsconfig.json`?

**Comment by lucifer1004** [comment]
There are both JS and TS projects using this library, so this issue is most probably related to your tsconfig.

**Comment by thejahweh** [comment]
I just can't imagine that finding the module typings is a problem with my tsconfig.

But it doesn't work anyway with Webpack and it doesn't matter if its not compiled by Webpack like all other vendors or if its compiled.

**Comment by lucifer1004** [comment]
More information is needed to locate the problem, so it would be very nice of you to share some configurations or your repo (if that's possible).

In addition, the error raised in your IDE is not about module typing, it said that the module could not be found.

**Comment by lucifer1004** [comment]
Close due to inactivity.
