### ISSUE TITLE
How can I force loading of the maps apis ?

### ISSUE THREAD

**Issue by MehdiSaffar** [googlemap-react/googlemap-react#19]
I have to use google apis like polyline etc.. before actually displaying the map.
How can I force the loading of the api?
Thanks

**Comment by lucifer1004** [comment]
I have decided to move the load of Google API to GoogleMapProvider (like I did in the `amap-react` project under this organization), but I have been too busy these days and do not have time to implement that.

**Comment by lucifer1004** [comment]
Currently, a workaround is to make the map invisible.

**Comment by MehdiSaffar** [comment]
I did the same hack, I added a GoogleMapsProvider as well as a map with `display: none` at the very top of my component tree, but when I open a second map I get 
![image](https://user-images.githubusercontent.com/13124263/64432936-2be46080-d0c6-11e9-8d50-e40ad1ce6953.png)
Do you please have another way for me to contact you? This is rather urgent. I would really appreciate your help

**Comment by lucifer1004** [comment]
@MehdiSaffar Yes, every context allows no more than one map instance, so that all other components can find the correct map instance. Glad that you have solved this problem.
