### ISSUE TITLE
React component as infowindow content

### ISSUE THREAD

**Issue by myleftshoe** [googlemap-react/googlemap-react#2]
Thanks for the lib, looks promising, although I started to use it to hopefully meet this requirement:
I am trying to render a link or button in an infoWindow that updates some react state - is/will this be possible?

```
<InfoWindow
   ...
   opts={{
      content: <div onClick={handleClick}>Clickable</div>,
    }}
/>
```

**Comment by myleftshoe** [comment]
I now realize it can be done with an OverlayView but it's a bit more work to create a custom popup and position it correctly. Still would be nice to be able to use an InfoWindow.

**Comment by lucifer1004** [comment]
Thanks for the issue! It should be possible, let me have a look.

**Comment by lucifer1004** [comment]
@myleftshoe There is a quick workaround, since `InfoWindowOptions.content` can be either an HTML `string` or a DOM `Node`, you can use `document.createElement('button')`. This is not good practice in a React project, but it is a workaround.

**Comment by lucifer1004** [comment]
It can be solved via React Portal, just like `OverlayView` or `CustomControl`, I am now working on tests, and the new version will be released soon.

**Comment by myleftshoe** [comment]
Perfect! better than using the content prop. Thanks for the super fast resolution. It's a fresh an easier to use lib than the alternatives.
