### ISSUE TITLE
Set Size of Markers

### ISSUE THREAD

**Issue by jamie-endeavour** [googlemap-react/googlemap-react#35]
Is there a way to set a custom size for Markers? I understand that with the Google Maps API you have to use the `Size()` method https://developers.google.com/maps/documentation/javascript/reference/marker#Icon but I'm unable to figure out a way to achieve this with this package.

I tried digging into the map object that's returned from the `GoogleMapContext` too but I've had no luck.

Am I missing something or would this be a new feature?

Thanks!

**Comment by lucifer1004** [comment]
You can just use `google.maps.Icon` to construct an icon with the desired size and pass it to `Marker`.

**Comment by jamie-endeavour** [comment]
Okay awesome, I don't suppose you could provide a quick example please?

**Comment by lucifer1004** [comment]
[![Edit google-map-icon-example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-fast-c3odz?fontsize=14&hidenavigation=1&theme=dark)

**Comment by jamie-endeavour** [comment]
:pray: thank you sorry I didn't realise it was as simple as passing a size like that. I appreciate the your time and help.
