### ISSUE TITLE
Example Usage is wrong

### ISSUE THREAD

**Issue by gilpanal** [googlemap-react/googlemap-react#5]
The code from the example Usage contains errors:

- import { ...  } from should be **'@googlemap-react/core'**
- MapBox is missing 
 style={{
        height: '100vh',
        width: '100%',
      }}

otherwise the component is not displayed

Thanks for your effort and the project! :)

**Comment by lucifer1004** [comment]
Thank you @gilpanal 
I have fixed the errors you mentioned.

**Comment by lucifer1004** [comment]
@all-contributors please add @gilpanal for bug
